# Manually builds rack-box virtual machine (dispatchable workflow)

name: RACK Build Virtual Machine Workflow
on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: 'dev'
        type: string

jobs:

# assemble-files job:
#  - Assembles files for rack-box builds

  assemble-files:
    uses: ./.github/workflows/assemble-files.yml

# assemble-turnstile-data job:
#  - Assembles Turnstile ingestion package
#  - Uploads ingestion package to artifacts

  assemble-turnstile-data:
    needs: assemble-files
    uses: ./.github/workflows/assemble-turnstile-data.yml
    secrets: inherit

# build-virtual-machine job:
#  - Builds rack-box virtual machine
#  - Uploads virtual machine to artifacts

  build-virtual-machine:
    needs: assemble-files
    uses: ./.github/workflows/build-virtual-machine.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
